// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import "dotenv/config";
import { defineConfig } from "prisma/config";
import * as dotenv from "dotenv"; // Добавляем импорт
dotenv.config(); // Загружаем переменные из .env в process.env

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // url: env("DATABASE_URL") || process.env.DATABASE_URL || "",
    url: process.env.DATABASE_URL || "",
  },
});
